#!/usr/bin/env ruby

def git
  dir = __dir__
  File.expand_path(File.join(dir, "cached_git"))
end

def main
  system("#{git} #{ARGV.join(" ")}")
  exit($?.exitstatus || 0)
end

if defined?(Bundler)
  Bundler.with_clean_env { main }
else
  main
end
